export const LEAD_FORM_REQUEST = "LEAD_FORM_REQUEST"
export const LEAD_FORM_SUCCESS = "LEAD_FORM_SUCCESS"
export const LEAD_FORM_FAIL = "LEAD_FORM_FAIL"


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"


export const FETCH_LEADS_REQUEST = "FETCH_LEADS_REQUEST"
export const FETCH_LEADS_SUCCESS = "FETCH_LEADS_SUCCESS"
export const FETCH_LEADS_FAIL = "FETCH_LEADS_FAIL"


export const OTP_REQUEST = "OTP_REQUEST"
export const OTP_SUCCESS = "OTP_SUCCESS"
export const OTP_FAIL = "OTP_FAIL"