export const COURSE_DATA = [
  {
    id: 0,
    title: "1. Why Choose Digital Aided School for Generative AI?",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },

  {
    id: 1,
    title: "2. What is the Program Cost?",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },

  {
    id: 2,
    title: "3. Program Duration and Structure",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 3,
    title: "4. How Does Learn Now, Pay Later Work?",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 4,
    title: "5. Time Commitment for the Program",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 5,
    title: "6. Catch Up on Missed Classes",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 6,
    title: "7. Certification Upon Program Completion",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 7,
    title: "8. Application Process",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  // {
  //   id: 8,
  //   title: "9. Payment Options Available",
  //   desc1: "Multiple Batches, hence time flexibility        ",
  //   desc2: "Multiple Batches, hence time flexibility        ",
  //   desc3: "Multiple Batches, hence time flexibility        ",
  //   desc4: "Multiple Batches, hence time flexibility        ",
  //   desc5: "Multiple Batches, hence time flexibility        ",
  //   desc6: "Multiple Batches, hence time flexibility        ",
  // },
];
export const COURSE_DATA2 = [
  {
    id: 9,
    title: "10. Payment Process After Placement",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 10,
    title: "11. Understanding Income Share Agreements",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 11,
    title: "12. Repayment Schedule for ISAs",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 12,
    title: "13. Eligibility for Generative AI Course",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 13,
    title: "14. Enrolling During College Early Years",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 14,
    title: "15. Switching to Generative AI with Work Experience",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 15,
    title: "16. Application Process Details",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
  {
    id: 16,
    title: "17. Evaluation Criteria for Applications",
    desc1: "Multiple Batches, hence time flexibility        ",
    desc2: "Multiple Batches, hence time flexibility        ",
    desc3: "Multiple Batches, hence time flexibility        ",
    desc4: "Multiple Batches, hence time flexibility        ",
    desc5: "Multiple Batches, hence time flexibility        ",
    desc6: "Multiple Batches, hence time flexibility        ",
  },
];
