import Image from 'next/image'
import styles from '../main/components/AboutUs.module.scss'
// import about from '../assets/aboutUs.svg'
import { FaQuoteLeft, FaQuoteRight } from 'react-icons/fa'
import Head from 'next/head'

function AboutUs() {
  return (
    <>
    <Head>
    <title>About Us</title>
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='/favicon.png' />
  </Head>
  <section className={styles.container}>
  <h1 className={styles.main_heading}>About Us</h1>
      <article className={styles.about}>
        <p className={styles.desc}>
          <FaQuoteLeft className={styles.quote} /> We are Digital Aided School
          team of Young professionals who believe in quality education and the
          latest technology. Learning is never-ending but learning what is
          required to keep body and soul together is principal, learning through
          technology where the resources are unlimited makes it more merrymaking
          <br />
          <br />
          We have the perfect & feasible solutions when it comes to EDUCATION &
          TECHNOLOGY. We have DIGITAL in our name (pun intended)
          <br />
          <br />
          For EDUCATION solutions, TECHNOLOGY solutions & DIGITAL solutions
          allow us to help with our plethora of band-aids as per your needs and
          requirements.
          <FaQuoteRight className={styles.quote} />
          </p>
          </article>
          </section>
          <hr/>
          </>
  )
}

export default AboutUs
