import Head from 'next/head'
import Banner from '../components/Banner'
import Blog from '../components/Blog'
import CoreFeature from '../components/CoreFeature'
import Feature from '../components/Feature'
// import Footer from '../components/Footer'
// import Header from '../components/Header'
import Package from '../components/Package'
import QualityFeature from '../components/QualityFeature'
import Services from '../components/Services'
import Subscribe from '../components/Subscribe'
import Team from '../components/Team'
import Testimonial from '../components/Testimonial'
import WorkFlow from '../components/WorkFlow'
import { default as MainBanner } from '../main/components/Banner';
import Header from '../main/components/Header';
import Courses from '../main/components/Courses';
import Footer from '../main/components/Footer';
import Misson from '../main/components/Misson'
import AboutProgram from '../main/components/AboutProgram'

export default function Home() {
  return (
    <main>
      {/* <Head>
        <title>Startup Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Feature />
      <Services />
      <QualityFeature />
      <CoreFeature />
      <Feature />
      <WorkFlow />
      <Package />
      <Team />
      <Testimonial />
      <Blog />
      <Subscribe />
      <Footer/> */}
      <Header/>
      <MainBanner/>
      <Courses />
      <Misson />
      <AboutProgram/>
      <Footer/>
    </main>
  )
}
